# Generated by Django 2.0.2 on 2018-04-27 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Organization/Name')),
                ('email', models.EmailField(default='n/a', max_length=50, unique=True)),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Organization/Name')),
                ('email', models.EmailField(default='n/a', max_length=50)),
                ('group_size', models.PositiveIntegerField(default=1)),
                ('reserved_date', models.DateField(help_text='Date to Reserve', verbose_name='Reservation Date')),
                ('start_time', models.TimeField(help_text='Tour Time Slot', verbose_name='Start of the Tour')),
                ('end_time', models.TimeField(help_text='End time of Tour', verbose_name='End of the Tour')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Date Published')),
                ('info_text', models.TextField(default='Other', max_length=256, verbose_name='Additional Info.')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_size', models.PositiveIntegerField(default=1)),
                ('date', models.DateField(help_text='Date to Reserve', verbose_name='Day of the Reservation')),
                ('start_time', models.TimeField(help_text='Tour Time Slot', verbose_name='Start of the Tour')),
                ('end_time', models.TimeField(help_text='End time of Tour', verbose_name='End of the Tour')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Date Published')),
                ('info_text', models.TextField(default='Other', max_length=256, verbose_name='Additional Info.')),
                ('docent', models.TextField(default='n/a', help_text='Assign a Docent to give the tour', max_length=256, verbose_name='Assigned Docent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.CustomerProfile')),
            ],
        ),
    ]
