# Generated by Django 2.0.2 on 2018-05-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docent',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Name')),
                ('email', models.EmailField(default='n/a', max_length=50, unique=True)),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
        ),
    ]
