# Generated by Django 2.0.2 on 2018-05-10 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_auto_20180510_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docent',
            old_name='slug',
            new_name='doc_slug',
        ),
    ]
