# Generated by Django 2.0.2 on 2018-05-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_auto_20180510_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docent',
            old_name='doc_slug',
            new_name='slug',
        ),
    ]
