# Generated by Django 2.0.2 on 2018-05-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_auto_20180510_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='actual_group_size',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
