# Generated by Django 2.0.2 on 2018-05-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_reservation_actual_group_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='actual_group_size',
            field=models.PositiveIntegerField(default=models.PositiveIntegerField(default=1)),
        ),
    ]
