# Generated by Django 2.0.2 on 2018-05-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_auto_20180510_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='actual_group_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
